/*/
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package byui.cit260.Memory2.frames;

import byui.cit260.Memory2.CardFrames.Card3;
import byui.cit260.Memory2.CardFrames.Card2;
import byui.cit260.Memory2.CardFrames.Card1;
import byui.cit260.Memory2.enums.GameStatus;
import byui.cit260.Memory2.menus.CardMenuControl;
import memory2.Player;
import memory2.PlayerB;

/**
 *
 * @author Karalee Foster
 */
public class BoardFrame extends javax.swing.JFrame {

    Player myPlayer = new Player();
    //PlayerB playerB = new PlayerB();
    String card1 = "";

//declare array
    /**
     * Creates new form BoardFrame
     */
    public BoardFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton7 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jbQuit = new javax.swing.JButton();
        jbScore = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jbCard1 = new javax.swing.JToggleButton();
        jbCard4 = new javax.swing.JToggleButton();
        jbCard2 = new javax.swing.JToggleButton();
        jbCard5 = new javax.swing.JToggleButton();
        jbCard3 = new javax.swing.JToggleButton();
        jbCard6 = new javax.swing.JToggleButton();

        jToggleButton7.setText("jToggleButton7");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Handwriting", 0, 24)); // NOI18N
        jLabel1.setText("Memory");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        jbQuit.setText("Quit");
        jbQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbQuitActionPerformed(evt);
            }
        });

        jbScore.setText("Score");
        jbScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbScoreActionPerformed(evt);
            }
        });

        jButton2.setText("help");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbQuit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbScore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbQuit)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jbCard1.setText("1");
        jbCard1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCard1ActionPerformed(evt);
            }
        });

        jbCard4.setText("4");
        jbCard4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCard4ActionPerformed(evt);
            }
        });

        jbCard2.setText("2");
        jbCard2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCard2ActionPerformed(evt);
            }
        });

        jbCard5.setText("5");
        jbCard5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCard5ActionPerformed(evt);
            }
        });

        jbCard3.setText("3");
        jbCard3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCard3ActionPerformed(evt);
            }
        });

        jbCard6.setText("6");
        jbCard6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCard6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbCard4, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(jbCard1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbCard5, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(jbCard2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbCard3, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(jbCard6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbCard1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbCard2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbCard3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCard4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCard5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCard6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbQuitActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_jbQuitActionPerformed

    private void jbCard1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCard1ActionPerformed


        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Card1().setVisible(true);
                if (card1.equals("")) { // checks to see what the card picked is 
                    card1 = "1";   //sets the value of the card picked
                } else {
                    if (card1.equals("5")) { // checks to see if the value of the second card picked is a match
                        myPlayer.addPoint(); // adds a point to the player
                        new MatchAlertFrame().setVisible(true);// match frame alert
                    } else {
                        new NotAMatch().setVisible(true);// not a match frame
                    }
                    card1 = ""; //resets the card
                }
            }
        });
        
    }//GEN-LAST:event_jbCard1ActionPerformed

    private void jbCard3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCard3ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Card2().setVisible(true);
                if (card1.equals("")) { // checks to see what the card picked is 
                    card1 = "3";   //sets the value of the card picked
                } else {
                    if (card1.equals("2")) { // checks to see if the value of the second card picked is a match
                        myPlayer.addPoint(); // adds a point to the player
                        new MatchAlertFrame().setVisible(true);// match frame alert
                    } else {
                        new NotAMatch().setVisible(true);// not a match frame
                    }
                    card1 = ""; //resets the card
                }
            }
        });
        
    }//GEN-LAST:event_jbCard3ActionPerformed

    private void jbCard2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCard2ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Card2().setVisible(true);
                if (card1.equals("")) { // checks to see what the card picked is 
                    card1 = "2";   //sets the value of the card picked
                } else {
                    if (card1.equals("3")) { // checks to see if the value of the second card picked is a match
                        myPlayer.addPoint(); // adds a point to the player
                        new MatchAlertFrame().setVisible(true);// match frame alert
                    } else {
                        new NotAMatch().setVisible(true);// not a match frame
                    }
                    card1 = ""; //resets the card
                }
            }
        });
        
    }//GEN-LAST:event_jbCard2ActionPerformed

    private void jbCard4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCard4ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Card3().setVisible(true);
                if (card1.equals("")) { // checks to see what the card picked is 
                    card1 = "4";   //sets the value of the card picked
                } else {
                    if (card1.equals("6")) { // checks to see if the value of the second card picked is a match
                        myPlayer.addPoint(); // adds a point to the player
                        new MatchAlertFrame().setVisible(true);// match frame alert
                    } else {
                        new NotAMatch().setVisible(true);// not a match frame
                    }
                    card1 = ""; //resets the card
                }
            }
        });
        
    }//GEN-LAST:event_jbCard4ActionPerformed

    private void jbCard5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCard5ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Card1().setVisible(true);
                if (card1.equals("")) { // checks to see what the card picked is 
                    card1 = "5";   //sets the value of the card picked
                } else {
                    if (card1.equals("1")) { // checks to see if the value of the second card picked is a match
                        myPlayer.addPoint(); // adds a point to the player
                        new MatchAlertFrame().setVisible(true);// match frame alert

                    } else {
                        new NotAMatch().setVisible(true);// not a match frame
                    }
                    card1 = ""; //resets the card
                }
            }
        });
        
    }//GEN-LAST:event_jbCard5ActionPerformed

    private void jbCard6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCard6ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Card3().setVisible(true);
                if (card1.equals("")) { // checks to see what the card picked is 
                    card1 = "6";   //sets the value of the card picked
                } else {
                    if (card1.equals("4")) { // checks to see if the value of the second card picked is a match
                        myPlayer.addPoint(); // adds a point to the player
                        new MatchAlertFrame().setVisible(true);// match frame alert
                    } else {
                        new NotAMatch().setVisible(true);// not a match frame
                    }
                    card1 = ""; //resets the card
                }
            }
        });
        
    }//GEN-LAST:event_jbCard6ActionPerformed

    private void jbScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbScoreActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScoreBoardFrame().setVisible(true);
            }
        });
    }//GEN-LAST:event_jbScoreActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HelpFrame().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BoardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BoardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BoardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BoardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BoardFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jbCard1;
    private javax.swing.JToggleButton jbCard2;
    private javax.swing.JToggleButton jbCard3;
    private javax.swing.JToggleButton jbCard4;
    private javax.swing.JToggleButton jbCard5;
    private javax.swing.JToggleButton jbCard6;
    private javax.swing.JButton jbQuit;
    private javax.swing.JButton jbScore;
    // End of variables declaration//GEN-END:variables
}
